from docker.xaas.ir/node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . . 

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait

RUN chmod +x /wait

CMD /wait && npm start
